#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""pipeline.stages -- Pipeline stage functions for the one-click pipeline."""

from __future__ import annotations

import argparse
import json
import shutil
import time
from pathlib import Path

from file_processor import read_file
from core.translation_db import TranslationDB
from core.lang_config import get_language_config
from core.font_patch import resolve_font, apply_font_patch, default_resources_fonts_dir
from core.file_safety import check_fstat_size

from pipeline.helpers import (
    _print,
    resolve_scan_root,
    list_rpy_files,
    pick_pilot_files,
    copy_subset_to_input,
    run_main,
    package_output,
)
# Round 42 M2 phase-3: 50 MB cap on the two internal report-JSON
# readers below (tl_mode_report.json / full report.json).  These reports
# are generated by prior pipeline stages and normally sit in the
# KB-low-MB range; a corrupt or absurdly large file would OOM
# json.loads before the existing try/except kicks in.  Matches the cap
# used by r37-r41 user-facing loaders for cross-module consistency.
_MAX_REPORT_JSON_SIZE = 50 * 1024 * 1024


from pipeline.gate import (
    evaluate_gate,
    collect_files_with_untranslated,
    collect_strings_stats,
    attribute_untranslated,
    write_report_summary_md,
)


def _run_retranslate_phase(
    full_translated_root: Path,
    stage2_translated: Path,
    pipeline_root: Path,
    args: argparse.Namespace,
    api_key: str,
) -> dict:
    """Stage 3: 漏翻补翻轮。返回 report["stages"]["retranslate"] 数据。"""
    untranslated_files = collect_files_with_untranslated(full_translated_root)
    result: dict = {"candidate_files": len(untranslated_files)}

    if not untranslated_files:
        _print("[INFO] 全量阶段无漏翻文件，跳过补翻")
        result["skipped"] = True
        result["checker_dropped"] = 0
        return result

    from translators.retranslator import (
        retranslate_file as _retranslate_file,
        find_untranslated_lines as _find_untranslated_lines,
    )
    from core.translation_utils import ProgressTracker as _ProgressTracker
    from core.api_client import APIClient as _APIClient, APIConfig as _APIConfig
    from core.glossary import Glossary as _Glossary

    rt_config = _APIConfig(
        provider=args.provider,
        api_key=api_key,
        model=args.model,
        rpm=args.rpm,
        rps=args.rps,
        timeout=args.timeout,
        temperature=0.1,
        max_response_tokens=args.max_response_tokens,
        custom_module=getattr(args, "custom_module", ""),
    )
    rt_client = _APIClient(rt_config)

    rt_glossary = _Glossary()
    rt_glossary_path = stage2_translated / "glossary.json"
    rt_glossary.load(str(rt_glossary_path))
    if args.dict:
        for dp in args.dict:
            rt_glossary.load_dict(dp)

    # Round 35 C1: ProgressTracker language namespace (same rationale as
    # the TranslationDB default_language threading — retranslate DB below).
    _rt_progress_lang = getattr(args, "target_lang", "zh") or "zh"
    rt_progress = _ProgressTracker(
        pipeline_root / "retranslate_progress.json",
        language=_rt_progress_lang,
    )
    rt_progress.data = {"completed_files": [], "completed_chunks": {}, "stats": {}}
    rt_progress.save()

    # Round 34: thread the caller's target_lang through so v1-era DB files
    # get migrated to v2 shape on load (forced backfill) and subsequent
    # upserts populate the ``language`` field consistently.
    _target_lang = getattr(args, "target_lang", "zh") or "zh"
    rt_db = TranslationDB(pipeline_root / "retranslate_db.json", default_language=_target_lang)
    rt_run_id = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime())

    # 用 find_untranslated_lines 精确扫描漏翻行
    rpy_files_all = sorted(list_rpy_files(full_translated_root))
    files_to_rt: list[tuple[Path, int]] = []
    total_ut = 0
    for f in rpy_files_all:
        ut = _find_untranslated_lines(read_file(f))
        if ut:
            files_to_rt.append((f, len(ut)))
            total_ut += len(ut)

    _print(f"[SCAN] 发现 {total_ut} 行漏翻，分布在 {len(files_to_rt)} 个文件中")

    rt_total_translated = 0
    rt_total_warnings: list[str] = []

    for idx, (rpy_path, n_ut) in enumerate(files_to_rt, 1):
        rel = rpy_path.relative_to(full_translated_root)
        _print(f"  [{idx}/{len(files_to_rt)}] {rel} ({n_ut} 行)")
        try:
            count, warnings = _retranslate_file(
                rpy_path,
                full_translated_root,
                full_translated_root,
                rt_client,
                rt_glossary,
                rt_progress,
                genre=args.genre,
                translation_db=rt_db,
                run_id=rt_run_id,
                stage="retranslate",
                provider=rt_config.provider,
                model=rt_config.model,
            )
            rt_total_translated += count
            rt_total_warnings.extend(warnings)
        except KeyboardInterrupt:
            rt_glossary.save(str(rt_glossary_path))
            rt_progress.save()
            rt_db.save()
            raise
        except Exception as e:
            _print(f"  [ERROR] {rel}: {e}")
            rt_total_warnings.append(str(e))

        if idx % 5 == 0:
            rt_glossary.save(str(rt_glossary_path))

    rt_glossary.save(str(rt_glossary_path))
    rt_db.save()

    _print(f"[RETRANSLATE] 补翻完成: {rt_total_translated} 条, "
           f"API 用量: {rt_client.usage.summary()}")

    result.update({
        "mode": "retranslate",
        "retranslated_files": len(files_to_rt),
        "total_untranslated_scanned": total_ut,
        "total_translated": rt_total_translated,
        "total_warnings": len(rt_total_warnings),
        "api_requests": rt_client.usage.total_requests,
        "input_tokens": rt_client.usage.total_input_tokens,
        "output_tokens": rt_client.usage.total_output_tokens,
        "estimated_cost_usd": round(rt_client.usage.estimated_cost, 4),
        "checker_dropped": 0,
    })
    return result


def _run_tl_mode_phase(
    project_root: Path,
    stage2_translated: Path,
    pipeline_root: Path,
    tl_lang: str,
    args: argparse.Namespace,
    api_key: str,
    report: dict,
    propagate_fn,
) -> None:
    """tl-mode 流水线：跳过试跑，直接全量 tl 翻译。"""
    _print("\n=== tl-mode 流水线 ===")
    _print(f"[TL] 语言目录: tl/{tl_lang}/")
    report["stages"]["pilot"] = {"skipped": True, "reason": "tl-mode 不需要试跑"}

    _print("\n=== Stage 1/2: tl-mode 全量翻译 ===")
    propagate_fn(stage2_translated)
    run_main(
        game_dir=project_root,
        output_dir=stage2_translated,
        provider=args.provider,
        api_key=api_key,
        model=args.model,
        genre=args.genre,
        workers=args.workers,
        rpm=args.rpm,
        rps=args.rps,
        timeout=args.timeout,
        max_chunk_tokens=args.max_chunk_tokens,
        max_response_tokens=args.max_response_tokens,
        log_file=pipeline_root / "tl_mode.log",
        resume=False,
        dict_paths=args.dict,
        excludes=args.exclude,
        copy_assets=args.copy_assets,
        target_lang=args.target_lang,
        stage="full",
        min_dialogue_density=args.min_dialogue_density,
        tl_mode=True,
        tl_lang=tl_lang,
    )

    tl_report_path = stage2_translated / "tl_mode_report.json"
    if tl_report_path.exists():
        try:
            tl_size = tl_report_path.stat().st_size
        except OSError:
            tl_size = 0
        if tl_size > _MAX_REPORT_JSON_SIZE:
            report["stages"]["tl_mode"] = {
                "error": (
                    f"tl_mode_report.json 过大 ({tl_size} > "
                    f"{_MAX_REPORT_JSON_SIZE})，视为损坏跳过"
                )
            }
        else:
            try:
                # Round 49 Step 2: TOCTOU defense via check_fstat_size on the open fd.
                with open(tl_report_path, encoding="utf-8") as f:
                    ok, fsize2 = check_fstat_size(f, _MAX_REPORT_JSON_SIZE)
                    if not ok:
                        report["stages"]["tl_mode"] = {
                            "error": (
                                f"tl_mode_report.json stat 后增长到 {fsize2} 字节"
                                f"（疑似 TOCTOU 攻击），超过 "
                                f"{_MAX_REPORT_JSON_SIZE} 字节上限"
                            )
                        }
                    else:
                        tl_report_data = json.loads(f.read())
                        report["stages"]["tl_mode"] = tl_report_data
            except (OSError, json.JSONDecodeError) as e:
                report["stages"]["tl_mode"] = {"error": f"无法读取 tl_mode_report.json: {e}"}
    else:
        report["stages"]["tl_mode"] = {"note": "tl_mode_report.json 未生成"}

    # tl-mode 完成后，如果启用了 --tl-screen 则自动补充 screen 翻译
    if getattr(args, "tl_screen", False):
        _print("\n=== tl-screen: 翻译 screen 裸英文 ===")
        from translators.screen import run_screen_translate
        run_screen_translate(args)
        report["stages"]["screen_translate"] = {"completed": True}

    report["stages"]["retranslate"] = {"skipped": True, "reason": "tl-mode 精度 99.97%，无需补翻"}
    _print("\n=== Stage 2/2: 报告与打包 ===")


def _run_pilot_phase(
    scan_root: Path,
    pilot_input: Path,
    pilot_output: Path,
    stage2_translated: Path,
    pipeline_root: Path,
    args: argparse.Namespace,
    api_key: str,
    report: dict,
    propagate_fn,
) -> None:
    """Stage 1: 试跑批次 + 闸门评估 + AI 术语提取。

    Raises: StageError if structural errors found
    """
    from pipeline.helpers import StageError

    pilot_files = pick_pilot_files(scan_root, args.pilot_count)
    if not pilot_files:
        raise StageError("未找到任何 .rpy 文件")
    copy_subset_to_input(scan_root, pilot_files, pilot_input)
    propagate_fn(pilot_output)

    run_main(
        game_dir=pilot_input,
        output_dir=pilot_output,
        provider=args.provider,
        api_key=api_key,
        model=args.model,
        genre=args.genre,
        workers=args.workers,
        rpm=args.rpm,
        rps=args.rps,
        timeout=args.timeout,
        max_chunk_tokens=args.max_chunk_tokens,
        max_response_tokens=args.max_response_tokens,
        log_file=pipeline_root / "pilot.log",
        resume=False,
        dict_paths=args.dict,
        excludes=args.exclude,
        copy_assets=args.copy_assets,
        target_lang=args.target_lang,
        stage="pilot",
        min_dialogue_density=args.min_dialogue_density,
    )

    pilot_translated_root = resolve_scan_root(pilot_output)
    gate1 = evaluate_gate(resolve_scan_root(pilot_input), pilot_translated_root)
    report["stages"]["pilot"] = {
        "files": len(pilot_files),
        "gate": gate1,
    }

    _print(
        "[GATE-PILOT] "
        f"errors={gate1['errors']} "
        f"warnings={gate1['warnings']} "
        f"untranslated={gate1['untranslated_total']} "
        f"ratio={gate1['untranslated_ratio']:.4f} "
        f"len_warns={gate1['len_ratio_warnings']} "
        f"len_ratio={gate1['len_ratio_warning_ratio']:.4f} "
        f"ph_order_warns={gate1['placeholder_order_warnings']}"
    )
    if gate1["errors"] > 0:
        raise StageError("试跑批次未通过：存在结构错误")
    pilot_ratio_exceeded = gate1["untranslated_ratio"] > args.gate_max_untranslated_ratio
    report["stages"]["pilot"]["ratio_exceeded"] = pilot_ratio_exceeded
    if pilot_ratio_exceeded:
        _print("[WARN ] 试跑漏翻占比超阈值，继续执行全量与增量轮再做最终判定")

    # 试跑后自动术语表提取
    try:
        from core.glossary import Glossary as _Glossary

        pilot_glossary = _Glossary()
        pilot_glossary_path = pilot_output / "glossary.json"
        pilot_glossary.load(str(pilot_glossary_path))

        pilot_db_path = pilot_output / "translation_db.json"
        if pilot_db_path.exists():
            # Round 34: pass default_language so a pre-r34 pilot DB gets v1→v2
            # backfill on load (prevents later upserts creating duplicate
            # (file,line,orig,None) + (file,line,orig,<lang>) entries).
            _pilot_lang = getattr(args, "target_lang", "zh") or "zh"
            pilot_db = TranslationDB(pilot_db_path, default_language=_pilot_lang)
            pilot_db.load()
            new_terms = pilot_glossary.extract_terms_from_translations(pilot_db.entries)
            if new_terms:
                added = pilot_glossary.auto_add_terms(new_terms)
                pilot_glossary.save(str(pilot_glossary_path))
                stage2_glossary_path = stage2_translated / "glossary.json"
                stage2_glossary_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(str(pilot_glossary_path), str(stage2_glossary_path))
                report["stages"]["pilot"]["auto_terms_extracted"] = len(new_terms)
                report["stages"]["pilot"]["auto_terms_added"] = added
                _print(f"[GLOSS] 从试跑结果自动提取 {len(new_terms)} 条术语，新增 {added} 条")
            else:
                _print("[GLOSS] 试跑结果中未发现可自动提取的术语")
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 自动术语提取失败（不影响后续流程）: {e}")


def _run_full_translation_phase(
    project_root: Path,
    scan_root: Path,
    stage2_translated: Path,
    pipeline_root: Path,
    args: argparse.Namespace,
    api_key: str,
    report: dict,
    propagate_fn,
) -> None:
    """Stage 2: 全量批处理 + 闸门评估。

    Raises: StageError if structural errors found
    """
    from pipeline.helpers import StageError

    propagate_fn(stage2_translated)
    run_main(
        game_dir=project_root,
        output_dir=stage2_translated,
        provider=args.provider,
        api_key=api_key,
        model=args.model,
        genre=args.genre,
        workers=args.workers,
        rpm=args.rpm,
        rps=args.rps,
        timeout=args.timeout,
        max_chunk_tokens=args.max_chunk_tokens,
        max_response_tokens=args.max_response_tokens,
        log_file=pipeline_root / "full.log",
        resume=False,
        dict_paths=args.dict,
        excludes=args.exclude,
        copy_assets=args.copy_assets,
        target_lang=args.target_lang,
        stage="full",
        min_dialogue_density=args.min_dialogue_density,
    )

    full_translated_root = resolve_scan_root(stage2_translated)
    gate2 = evaluate_gate(scan_root, full_translated_root)
    report["stages"]["full"] = {"gate": gate2}
    try:
        full_report_path = stage2_translated / "report.json"
        if full_report_path.exists():
            # Round 42 M2 phase-3: size gate before json.loads.
            try:
                full_size = full_report_path.stat().st_size
            except OSError:
                full_size = 0
            if full_size > _MAX_REPORT_JSON_SIZE:
                raise ValueError(
                    f"full report.json 过大 ({full_size} > "
                    f"{_MAX_REPORT_JSON_SIZE})，视为损坏跳过"
                )
            # Round 49 Step 2: TOCTOU defense via check_fstat_size on the open fd.
            with open(full_report_path, encoding="utf-8") as f:
                ok, fsize2 = check_fstat_size(f, _MAX_REPORT_JSON_SIZE)
                if not ok:
                    raise ValueError(
                        f"full report.json stat 后增长到 {fsize2} 字节"
                        f"（疑似 TOCTOU 攻击），超过 "
                        f"{_MAX_REPORT_JSON_SIZE} 字节上限"
                    )
                full_report = json.loads(f.read())
            report["stages"]["full"]["checker_dropped"] = int(full_report.get("total_checker_dropped", 0))
            report["stages"]["full"]["chunk_stats"] = full_report.get("chunk_stats", {})
        else:
            report["stages"]["full"]["checker_dropped"] = 0
            report["stages"]["full"]["report_note"] = "full report.json 未生成（跳过 checker 统计）"
    except (OSError, json.JSONDecodeError, KeyError, ValueError) as e:
        # Previously this branch silently zeroed out checker_dropped; surface
        # the failure so pipeline consumers don't mistake corrupted data for
        # "zero dropped items". (Round 26 H-3)
        _print(f"[WARN ] 解析 full report.json 失败，checker 统计降级为 0: {e}")
        report["stages"]["full"]["checker_dropped"] = 0
        report["stages"]["full"]["report_error"] = f"{type(e).__name__}: {e}"
    _print(
        "[GATE-FULL] "
        f"errors={gate2['errors']} "
        f"warnings={gate2['warnings']} "
        f"untranslated={gate2['untranslated_total']} "
        f"ratio={gate2['untranslated_ratio']:.4f} "
        f"len_warns={gate2['len_ratio_warnings']} "
        f"len_ratio={gate2['len_ratio_warning_ratio']:.4f} "
        f"ph_order_warns={gate2['placeholder_order_warnings']}"
    )
    if gate2["errors"] > 0:
        raise StageError("全量批处理未通过：存在结构错误")


# ============================================================
# 默认语言设置
# ============================================================

def _generate_default_language(output_game_dir: Path, target_lang: str) -> bool:
    """在输出 game/ 目录中生成 default_language.rpy，设置游戏默认语言。

    如果文件已存在则跳过（避免覆盖用户自定义配置）。
    返回 True 表示生成成功，False 表示跳过。
    """
    dest = output_game_dir / "default_language.rpy"
    if dest.exists():
        _print(f"[LANG] default_language.rpy 已存在，跳过: {dest}")
        return False

    # 从 lang_config 获取 Ren'Py 使用的语言名
    # Ren'Py 的 config.default_language 使用 tl/ 子目录名，
    # 通常是 field_aliases 中的第二个（如 "chinese", "japanese" 等）
    lc = get_language_config(target_lang)
    # 选择 Ren'Py tl/ 子目录名（= config.default_language 的值）。
    # 优先级：纯字母长名（"chinese"/"japanese"）> 含下划线长名（"traditional_chinese"）> 最长别名 > code
    lang_name = None
    for alias in lc.field_aliases:
        if len(alias) > 3 and alias.isalpha():
            lang_name = alias
            break
    if lang_name is None:
        # 含下划线的长名（如 "traditional_chinese"），取最长的以跳过短代码如 "zh_tw"
        underscore_candidates = [
            a for a in lc.field_aliases
            if len(a) > 3 and "_" in a and a.replace("_", "").isalpha()
        ]
        if underscore_candidates:
            lang_name = max(underscore_candidates, key=len)
    if lang_name is None:
        lang_name = max(lc.field_aliases, key=len) if lc.field_aliases else lc.code

    content = (
        f'# Auto-generated by translation pipeline — sets default language\n'
        f'init python:\n'
        f'    config.default_language = "{lang_name}"\n'
    )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    _print(f"[LANG] 生成 default_language.rpy: config.default_language = \"{lang_name}\"")
    return True


# ============================================================
# Lint 修复集成
# ============================================================

def _run_lint_repair_phase(
    game_dir: Path,
    report: dict,
) -> None:
    """翻译后自动运行 Ren'Py lint 检测并修复语法错误。

    如果 lint 不可用（找不到游戏引擎 Python），则跳过并明确告知。
    """
    from tools.renpy_lint_fixer import is_lint_available, run_lint

    if not is_lint_available(game_dir):
        _print(
            "[LINT] Lint 修复已跳过：未找到 Ren'Py 引擎 Python。"
            f"如需 lint 修复，请确保 {game_dir} 包含完整游戏目录（含 lib/ 和 game/），"
            "然后手动运行: python -m tools.renpy_lint_fixer <game_dir>"
        )
        report["stages"]["lint_repair"] = {"skipped": True, "reason": "Ren'Py engine not found"}
        return

    _print("[LINT] 运行 Ren'Py lint 修复...")
    result = run_lint(game_dir)

    lint_report = {
        "available": result.available,
        "passes": result.passes,
        "total_fixes": len(result.fixes),
        "errors_remaining": result.errors_remaining,
    }
    report["stages"]["lint_repair"] = lint_report

    if result.fixes:
        _print(f"[LINT] 修复了 {len(result.fixes)} 个语法错误（{result.passes} 轮迭代）")
    elif result.errors_remaining > 0:
        _print(f"[LINT] 发现 {result.errors_remaining} 个错误但无法自动修复")
    else:
        _print("[LINT] 无语法错误")


def _run_final_report(
    scan_root: Path,
    stage2_translated: Path,
    project_out_root: Path,
    pipeline_root: Path,
    pilot_output: Path,
    args: argparse.Namespace,
    report: dict,
    t0: float,
) -> bool:
    """最终闸门、归因分析、报告生成、打包。返回是否通过。"""
    full_translated_root = resolve_scan_root(stage2_translated)
    gate3 = evaluate_gate(scan_root, full_translated_root)
    report["stages"]["final_gate"] = gate3
    _print(
        "[GATE-FINAL] "
        f"errors={gate3['errors']} "
        f"warnings={gate3['warnings']} "
        f"untranslated={gate3['untranslated_total']} "
        f"ratio={gate3['untranslated_ratio']:.4f} "
        f"len_warns={gate3['len_ratio_warnings']} "
        f"len_ratio={gate3['len_ratio_warning_ratio']:.4f} "
        f"ph_order_warns={gate3['placeholder_order_warnings']}"
    )

    # Strings 翻译统计视图
    try:
        strings_stats = collect_strings_stats(full_translated_root)
        report["stages"]["strings_stats"] = strings_stats
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 收集 strings 统计时出错: {e}")

    ok = gate3["errors"] == 0 and gate3["untranslated_ratio"] <= args.gate_max_untranslated_ratio

    # 打包前自动字体补丁（可选）
    if getattr(args, "patch_font", False):
        resources_fonts = default_resources_fonts_dir()
        font_path = resolve_font(resources_fonts, args.font_file or None)
        if font_path:
            output_game = resolve_scan_root(stage2_translated)
            apply_font_patch(output_game, scan_root, font_path)

    # 打包前生成 default_language.rpy（设置游戏默认语言）
    try:
        output_game = resolve_scan_root(stage2_translated)
        target_lang = getattr(args, "target_lang", "zh")
        _generate_default_language(output_game, target_lang)
    except OSError as e:
        _print(f"[WARN ] 生成 default_language.rpy 失败: {e}")

    # 打包前运行 lint 修复（需要原始游戏目录，非输出目录）
    if not getattr(args, "no_lint_repair", False):
        try:
            _run_lint_repair_phase(scan_root, report)
        except Exception as e:
            _print(f"[WARN ] Lint 修复阶段异常: {e}")
            report["stages"]["lint_repair"] = {"error": str(e)}

    report["stages"]["package"] = {}
    package_path = package_output(stage2_translated, args.package_name)
    report["stages"]["package"]["zip"] = str(package_path)

    report["success"] = ok
    report["elapsed_seconds"] = round(time.time() - t0, 2)

    report_path = project_out_root / "pipeline_report.json"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    # 合并各阶段 translation_db.json
    project_db = None
    try:
        # Round 34: project-level merge target gets default_language so
        # its own v1→v2 backfill runs; sub_dbs below also pass it so any
        # still-v1 per-stage DB adopts the run's target language on load.
        _merge_lang = getattr(args, "target_lang", "zh") or "zh"
        project_db = TranslationDB(project_out_root / "translation_db.json", default_language=_merge_lang)
        project_db.load()
        db_paths_to_merge = [
            pilot_output / "translation_db.json",
            stage2_translated / "translation_db.json",
            pipeline_root / "retranslate_db.json",
        ]
        for db_path in db_paths_to_merge:
            if not db_path.exists():
                continue
            sub_db = TranslationDB(db_path, default_language=_merge_lang)
            sub_db.load()
            project_db.add_entries(sub_db.entries)
        project_db.save()
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 合并 translation_db.json 失败: {e}")

    # 漏翻归因分析
    try:
        if project_db and project_db.entries:
            attribution = attribute_untranslated(full_translated_root, project_db)
        else:
            attribution = {
                "total": 0, "ai_missing": 0, "checker_dropped": 0,
                "write_fail": 0, "unknown": 0, "db_entries_count": 0,
                "note": "translation_db 为空，无法逐行归因",
            }
        report["stages"]["attribution"] = attribution
        if attribution["total"] > 0:
            _print(
                f"[ATTRIBUTION] 漏翻归因: 总计 {attribution['total']} | "
                f"AI未返回 {attribution['ai_missing']} "
                f"({attribution['ai_missing'] / attribution['total'] * 100:.1f}%) | "
                f"Checker丢弃 {attribution['checker_dropped']} "
                f"({attribution['checker_dropped'] / attribution['total'] * 100:.1f}%) | "
                f"回写失败 {attribution['write_fail']} "
                f"({attribution['write_fail'] / attribution['total'] * 100:.1f}%) | "
                f"未知 {attribution['unknown']} "
                f"({attribution['unknown'] / attribution['total'] * 100:.1f}%)"
            )
        else:
            _print("[ATTRIBUTION] 无漏翻条目需要归因")
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 漏翻归因分析失败: {e}")

    # HTML 校对报告
    try:
        from tools.review_generator import generate_review_html
        db_merged_path = project_out_root / "translation_db.json"
        if db_merged_path.exists():
            review_path = project_out_root / "review.html"
            review_count = generate_review_html(db_merged_path, review_path)
            report["stages"]["review_html"] = {"path": str(review_path), "entries": review_count}
            _print(f"[REVIEW] 生成校对报告: {review_path} ({review_count} 条)")
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 生成 review.html 失败: {e}")

    # 结构化 Markdown 概要
    try:
        write_report_summary_md(
            project_out_root=project_out_root,
            report=report,
            gate_max_untranslated_ratio=args.gate_max_untranslated_ratio,
        )
    except (OSError, json.JSONDecodeError, ValueError, TypeError) as e:
        _print(f"[WARN ] 生成 report_summary.md 失败: {e}")

    # 重新写入 pipeline_report.json（归因分析等后续数据已追加到 report dict）
    try:
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    except OSError as e:
        _print(f"[WARN ] 写入 pipeline_report.json 失败: {e}")

    _print(f"\n[REPORT] {report_path}")
    return ok
